### ISSUE TITLE
Can multiple dongles and modlets in the same area be a problem?

### ISSUE THREAD

**Issue by spiff72** [mcolyer/hacklet#13]
Hello again, 

I have a question about how to use multiple modlet outlets in the same environment, but with SEPARATE dongles and a separate RasPi running it.

I use these so I can integrate some "system" commands into the Octoprint interface that allow me to either turn off my 3D printer or a light that shines on the printer for the purpose of a webcam stream.

I initially had this working on the second pi (which was an identical clone copy of the first, including all the hacklet setup).  I just ran the "hacklet commission" command and noted the network ID hex code and changed my scripts to use that code instead of the one originally configured.

However, when I moved the modlet receptacle from the place I was testing it in to its new location, the commands don't appear to work anymore.  I can try recommissioning it, but I haven't seen that happen in the 3-ish years I have been running it on RasPi number one.

Could the fact that I have two dongles in the same room cause this?  The commands are all still working fine on my older RasPi, and it was unplugged to move it this past weekend too...

Thanks!

**Comment by spiff72** [comment]
I should add that the modlet is blinking red every two seconds.  I can't recommission until the print i have running is done (in case it shuts the power off inadvertently)...

**Comment by spiff72** [comment]
Ugh - sorry.  Apparently that blinking light means that it was overridden, so I might need to just push the button after this print is done and it might work again.

**Comment by spiff72** [comment]
It was indeed overridden.  I pressed the button and the blinking stopped.  The scripts to turn printer and light on/off are now working.  Closing.

**Comment by mcolyer** [comment]
Glad you were able to figure it out.
