### ISSUE TITLE
USB error

### ISSUE THREAD

**Issue by soundswarm** [mcolyer/hacklet#9]
When I run "hacklet commission" I get the following error.  It's a bit challenging to debug and I'm wondering if you have any suggestions on how to fix it.   Thanks!:

```
/Users/s/.rvm/gems/ruby-2.1.2/gems/libftdi-ruby-0.0.20/lib/ftdi.rb:407:in `check_result': -5: unable to claim usb device. Make sure the default FTDI driver is not in use (Ftdi::StatusCodeError)

    from /Users/s/.rvm/gems/ruby-2.1.2/gems/libftdi-ruby-0.0.20/lib/ftdi.rb:178:in `usb_open'
from /Users/s/.rvm/gems/ruby-2.1.2/gems/hacklet-0.6.0/lib/hacklet/serial_connection.rb:8:in `initialize'
from /Users/s/.rvm/gems/ruby-2.1.2/gems/hacklet-0.6.0/lib/hacklet/dongle.rb:14:in `new'
from /Users/s/.rvm/gems/ruby-2.1.2/gems/hacklet-0.6.0/lib/hacklet/dongle.rb:14:in `open'
from /Users/s/.rvm/gems/ruby-2.1.2/gems/hacklet-0.6.0/bin/hacklet:12:in `<top (required)>'
from /usr/local/bin/hacklet:23:in `load'
from /usr/local/bin/hacklet:23:in `<main>'
```

**Comment by mcolyer** [comment]
It sounds like something else might be grabbing the USB port. Which OS are you on?

**Comment by soundswarm** [comment]
Mac, Yosemite

On Nov 7, 2015, at 07:56, Matt Colyer notifications@github.com wrote:

It sounds like something else might be grabbing the USB port. Which OS are you on?

**Comment by mcolyer** [comment]
It looks like there's a page about [fixing this](http://pylibftdi.readthedocs.org/en/latest/troubleshooting.html). I'm going to go ahead and close this out as it looks like that should resolve your issue.

**Comment by soundswarm** [comment]
Thanks!

On Nov 7, 2015, at 08:34, Matt Colyer notifications@github.com wrote:

It looks like there's a page about fixing this. I'm going to go ahead and close this out as it looks like that should resolve your issue.
